server:
  port: 8083
  error:
    include-message: always
spring:
  application:
    name: clients
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        input:
          destination: sendTransaction
          binder: local_rabbit
          consumer:
            maxAttempts: 1
            concurrency: 1
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: ${SPRING_RABBITMQ_HOST:localhost}
                port: 5672
                username: guest
                password: guest
                virtual-host: /

eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOST:${HOST:localhost}}:${DISCOVERY_PORT:8761}/eureka/