server:
  port: 8083
spring:
  application:
    name: clients
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        input:
          destination: sendTransaction
          group: transactionQueue

eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOST:${HOST:localhost}}:${DISCOVERY_PORT:8761}/eureka/